### ISSUE TITLE
cannot install on outlook 2016 desktop version

### ISSUE THREAD

**Issue by sasagr** [alessiobianchini/outlook-openai-add-in#1]
I have tried to install this add-in on my outlook 2016 desktop version.
After git clone and npm install and npm start I get this error and log.
Is there anything that can be done to make it working? Thanks

-------------------------------

C:\Users\sasag\outlook-openai-add-in>npm start

> doit-ai-office-addin@1.0.0 start C:\Users\sasag\outlook-openai-add-in
> office-addin-debugging start manifest.xml

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'node:net'
Require stack:
- C:\Users\sasag\outlook-openai-add-in\node_modules\mkcert\dist\mkcert.js
- C:\Users\sasag\outlook-openai-add-in\node_modules\office-addin-dev-certs\lib\generate.js
- C:\Users\sasag\outlook-openai-add-in\node_modules\office-addin-dev-certs\lib\main.js
- C:\Users\sasag\outlook-openai-add-in\node_modules\office-addin-debugging\lib\start.js
- C:\Users\sasag\outlook-openai-add-in\node_modules\office-addin-debugging\lib\commands.js
- C:\Users\sasag\outlook-openai-add-in\node_modules\office-addin-debugging\lib\cli.js
- C:\Users\sasag\outlook-openai-add-in\node_modules\office-addin-debugging\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module.patchedRequire [as require] (C:\Users\sasag\outlook-openai-add-in\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\sasag\outlook-openai-add-in\node_modules\mkcert\dist\mkcert.js:8:36)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\mkcert\\dist\\mkcert.js',
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\office-addin-dev-certs\\lib\\generate.js',
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\office-addin-dev-certs\\lib\\main.js',
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\office-addin-debugging\\lib\\start.js',
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\office-addin-debugging\\lib\\commands.js',
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\office-addin-debugging\\lib\\cli.js',
    'C:\\Users\\sasag\\outlook-openai-add-in\\node_modules\\office-addin-debugging\\cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doit-ai-office-addin@1.0.0 start: `office-addin-debugging start manifest.xml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the doit-ai-office-addin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sasag\AppData\Roaming\npm-cache\_logs\2024-12-17T07_47_23_897Z-debug.log

C:\Users\sasag\outlook-openai-add-in>

---------------------------

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle doit-ai-office-addin@1.0.0~prestart: doit-ai-office-addin@1.0.0
6 info lifecycle doit-ai-office-addin@1.0.0~start: doit-ai-office-addin@1.0.0
7 verbose lifecycle doit-ai-office-addin@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle doit-ai-office-addin@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\sasag\outlook-openai-add-in\node_modules\.bin;C:\ffmpeg\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jre1.8.0_271\bin;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\Users\sasag\AppData\Local\Microsoft\WindowsApps;C:\Users\sasag\AppData\Roaming\npm;C:\Users\sasag\AppData\Roaming\Amazon;C:\Users\sasag\nim-1.4.2\bin;C:\Users\sasag\.nimble\bin;C:\Users\sasag\AppData\Local\Programs\Fiddler;C:\Users\sasag\.dotnet\tools;C:\Program Files\WireGuard\;C:\Program Files\Tailscale\;C:\Program Files\Calibre2\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\sasag\AppData\Local\Microsoft\WindowsApps;C:\Users\sasag\AppData\Roaming\npm;C:\Users\sasag\AppData\Roaming\Amazon;C:\Users\sasag\nim-1.4.2\bin;C:\Users\sasag\.nimble\bin;C:\Users\sasag\AppData\Local\Programs\Fiddler;C:\Users\sasag\.dotnet\tools;C:\ffmpeg\bin;C:\Users\sasag\AppData\Local\Microsoft\WindowsApps;C:\Users\sasag\AppData\Local\Programs\Ollama;C:\Users\sasag\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sasag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts;
9 verbose lifecycle doit-ai-office-addin@1.0.0~start: CWD: C:\Users\sasag\outlook-openai-add-in
10 silly lifecycle doit-ai-office-addin@1.0.0~start: Args: [ '/d /s /c', 'office-addin-debugging start manifest.xml' ]
11 silly lifecycle doit-ai-office-addin@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle doit-ai-office-addin@1.0.0~start: Failed to exec start script
13 verbose stack Error: doit-ai-office-addin@1.0.0 start: `office-addin-debugging start manifest.xml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid doit-ai-office-addin@1.0.0
15 verbose cwd C:\Users\sasag\outlook-openai-add-in
16 verbose Windows_NT 10.0.19045
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error doit-ai-office-addin@1.0.0 start: `office-addin-debugging start manifest.xml`
22 error Exit status 1
23 error Failed at the doit-ai-office-addin@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by alessiobianchini** [comment]
Hi @sasagr, can you post your node version using `node -v`? 
Thanks

**Comment by alessiobianchini** [comment]
@sasagr from logs I found this: `verbose node v12.18.3`. 
This likely happens if the Node.js version is below 16.0.0, as the node: prefix was introduced in version 16.
Can you try updating node?

**Comment by sasagr** [comment]
updated it but now I have another error.

----------------------------
C:\Users\sasag\outlook-openai-add-in>npm start

> doit-ai-office-addin@1.0.0 start
> office-addin-debugging start manifest.xml

(node:9584) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Debugging is being started...
App type: desktop
Enabled debugging for add-in 8d59c4b4-eded-4873-939a-880cf49d97e6.
The dev server is already running on port 3000.
Sideloading the Office Add-in...
running: npx @microsoft/teamsapp-cli install --xml-path "C:\Users\sasag\outlook-openai-add-in\manifest.xml"

Log in to your Microsoft 365 account - opening default web browser at https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0&scope=https%3A%2F%2Ftitles.prod.mos.microsoft.com%2F.default%20openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A57621&client-request-id=a3110706-5651-4baf-923f-ed8a08338890&response_mode=query&response_type=code&x-client-SKU=msal.js.node&x-client-VER=2.6.6&x-client-OS=win32&x-client-CPU=x64&client_info=1&code_challenge=mYnMOueoo8ee1BchNatRqjcKS1rktb_cw8zo7ezP2KI&code_challenge_method=S256&prompt=select_account#

[Login] Failed to retrieve token silently. If you encounter this problem multiple times, you can delete `C:\Users\sasag\.fx\account` and try again. invalid_scope: 70011 - [2024-12-17 10:08:17Z]: AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://dev.teams.microsoft.com/AppDefinitions.ReadWrite openid profile offline_access' does not exist. Trace ID: b3994daa-2db4-4eee-b5da-cc9651ccda02 Correlation ID: d659bfd7-1994-46ea-bf5f-241669ee7b92 Timestamp: 2024-12-17 10:08:17Z - Correlation ID: d659bfd7-1994-46ea-bf5f-241669ee7b92 - Trace ID: b3994daa-2db4-4eee-b5da-cc9651ccda02

--Error sideloading!--
Error: Error: Command failed: npx @microsoft/teamsapp-cli install --xml-path "C:\Users\sasag\outlook-openai-add-in\manifest.xml"
(node:20548) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20548) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(×) Error: Get ServiceUrl failed. Request failed with status code 403
(×) Error: m365.InternalError: Request failed with status code 403 (tracingId: ) :

STDERR:
(node:20548) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20548) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(×) Error: Get ServiceUrl failed. Request failed with status code 403
(×) Error: m365.InternalError: Request failed with status code 403 (tracingId: ) :

Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Command failed: npx @microsoft/teamsapp-cli install --xml-path "C:\Users\sasag\outlook-openai-add-in\manifest.xml"
(node:20548) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20548) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(×) Error: Get ServiceUrl failed. Request failed with status code 403
(×) Error: m365.InternalError: Request failed with status code 403 (tracingId: ) :

-----------------------------

I tried to delete C:\Users\sasag\.fx\account but got the same message. The webpack terminal windows started without issues.

**Comment by alessiobianchini** [comment]
I think you have some problems related to auth configuration: 
`[Login] Failed to retrieve token silently. If you encounter this problem multiple times, you can delete C:\Users\sasag\.fx\account and try again. invalid_scope: 70011 - [2024-12-17 10:08:17Z]: AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://dev.teams.microsoft.com/AppDefinitions.ReadWrite openid profile offline_access' does not exist. Trace ID: b3994daa-2db4-4eee-b5da-cc9651ccda02 Correlation ID: d659bfd7-1994-46ea-bf5f-241669ee7b92 Timestamp: 2024-12-17 10:08:17Z - Correlation ID: d659bfd7-1994-46ea-bf5f-241669ee7b92 - Trace ID: b3994daa-2db4-4eee-b5da-cc9651ccda02`

You can try:
- Remove the folder C:\Users\sasag\.fx\account completely.
- Ensure proper permissions: Confirm that your Microsoft account has the required scopes for sideloading (AppDefinitions.ReadWrite).
 - Fix invalid scope: Modify the scope in the authentication call (likely in a manifest or config file). Replace https://dev.teams.microsoft.com/AppDefinitions.ReadWrite with the correct scope for your app.
